version: "3.7"

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=finances
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - ./volumes/database:/var/lib/mysql

